#Выбор браузера:
browser: chrome
sleep: 3

#Тестовый сайт:
address: https://test-stand.gb.ru/login

#Пользовательские данные:
login_valid: ANTA
login_invalid: AN
password_valid: 95ed42eb5c
password_invalid: dsadfds

#Название директории для сохранения скриншотов:
directory_screenshot: screenshot

#Локаторы страницы входа:
username: //input[@type="text"]
password: //input[@type="password"]
button_login: button
error: //*[@id="app"]/main/div/div/div[2]/h2
input_field_height: span.mdc-text-field__ripple
login_button_color: //button[@type="submit"]

#Локаторы домашней страницы пользователя:
account_name: //*[@id="app"]/main/nav/ul/li[3]
button_create_new_post: create-btn
contact: //*[@id="app"]/main/nav/ul/li[2]
button_logout: //*[@id="app"]/main/nav/ul/li[3]/div/ul/li[3]/span[2]

#Локаторы создание поста:
field_title: //*[@id="create-item"]/div/div/div[1]/div/label
field_description: //*[@id="create-item"]/div/div/div[2]/div/label
field_content: //*[@id="create-item"]/div/div/div[3]/div/label
save_post_button: //*[@id="create-item"]/div/div/div[7]/div/button
title_on_the_page: h1.svelte-tv8alb


#Локаторы формы "Contact":
form_name: //*[@id="app"]/main/div/div/h1
field_your_name: //*[@id="contact"]/div[1]/label
field_your_email: //*[@id="contact"]/div[2]/label
field_your_content: //*[@id="contact"]/div[3]/label
contact_us_button: //*[@id="contact"]/div[4]/button