address: https://test-stand.gb.ru/login
sleep: 3
browser: chrome
directory_screenshot: screenshot
login_valid: ANTA
login_invalid: AN


username: //input[@type="text"]
password: //input[@type="password"]
button_login: //button[@form="login"]
error: //*[@id="app"]/main/div/div/div[2]/h2


input_field_height: span.mdc-text-field__ripple
login_button_color: //button[@type="submit"]
account_name: //*[@id="app"]/main/nav/ul/li[3]/a


button_create_new_post: create-btn
field_title: //*[@id="create-item"]/div/div/div[1]/div/label
field_description: //*[@id="create-item"]/div/div/div[2]/div/label
field_content: //*[@id="create-item"]/div/div/div[3]/div/label
save_post_button: //*[@id="create-item"]/div/div/div[7]/div/button
post_titles_on_the_page: h1.svelte-tv8alb