#Выбор браузера:
browser: chrome
sleep: 3

# Тестовые данные для API
wsdl: https://speller.yandex.net/services/spellservice?WSDL
url_login: https://test-stand.gb.ru/gateway/login
url_posts: https://test-stand.gb.ru/api/posts


#Тестовый сайт:
address: https://test-stand.gb.ru/login

#Пользовательские данные:
login_valid: ANTA
login_invalid: AN
password_valid: 95ed42eb5c
password_invalid: dsadfds

#Название директории для сохранения скриншотов:
directory_screenshot: screenshot

XPATH:
  #Локаторы домашней страницы пользователя:
  LOCATOR_ACCOUNT_NAME: //*[@id="app"]/main/nav/ul/li[3]
  LOCATOR_CONTACT: //*[@id="app"]/main/nav/ul/li[2]
  LOCATOR_BUTTON_LOGOUT: //*[@id="app"]/main/nav/ul/li[3]/div/ul/li[3]/span[2]

  #Локаторы страницы входа:
  LOCATOR_LOGIN_FIELD: //input[@type="text"]
  LOCATOR_PASSWORD_FIELD: //input[@type="password"]
  LOCATOR_ERROR_MESSAGE: //*[@id="app"]/main/div/div/div[2]/h2
  LOCATOR_LOGIN_BUTTON_COLOR: //button[@type="submit"]

  #Локаторы создание поста:
  LOCATOR_FIELD_TITLE: //*[@id="create-item"]/div/div/div[1]/div/label
  LOCATOR_FIELD_DESCRIPTION: //*[@id="create-item"]/div/div/div[2]/div/label
  LOCATOR_FIELD_CONTENT: //*[@id="create-item"]/div/div/div[3]/div/label
  LOCATOR_SAVE_POST_BUTTON: //*[@id="create-item"]/div/div/div[7]/div/button

  #Локаторы формы "Contact":
  LOCATOR_FORM_NAME: //*[@id="app"]/main/div/div/h1
  LOCATOR_FIELD_YOUR_NAME: //*[@id="contact"]/div[1]/label
  LOCATOR_FIELD_YOUR_EMAIL: //*[@id="contact"]/div[2]/label
  LOCATOR_FIELD_YOUR_CONTENT: //*[@id="contact"]/div[3]/label
  LOCATOR_CONTACT_US_BUTTON: //*[@id="contact"]/div[4]/button
CSS:
  #Локаторы страницы входа:
  LOCATOR_BUTTON_LOGIN: button
  LOCATOR_INPUT_FIELD_HEIGHT: span.mdc-text-field__ripple

  #Локаторы создание поста:
  LOCATOR_TITLE_ON_THE_PAGE: h1.svelte-tv8alb
ID:
  #Локаторы домашней страницы пользователя:
  LOCATOR_CREATE_NEW_POST: create-btn